In [108]:
import numpy as np

In [109]:
np.array([23,45,234,65,766,87]) #array

array([ 23,  45, 234,  65, 766,  87])

In [110]:
n = np.array([23,45,234,65,766,87]) #vector
print(n)

[ 23  45 234  65 766  87]


In [111]:
type(n)

numpy.ndarray

In [112]:
#Tensor

n3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [113]:
type(n3)

numpy.ndarray

## dtype


In [ ]:
np.array([1,2,3],dtype = bool)

In [ ]:
np.array([1,2,3],dtype = complex)

## arrange

In [ ]:
np.arange(1,30)

In [ ]:
np.arange(0,31,3)

## reshape

In [ ]:
r1 = np.arange(0,15).reshape(3,5)
print(r1)

In [ ]:
#3d Tensor
r2 = np.arange(8 , dtype = int).reshape(2,2,2)
print(r2)

## ones and zeroes

default datatype is float

In [ ]:
o = np.ones((3,4),dtype = int)
print(o,type(o))

In [ ]:
z = np.zeros((4,5),dtype = complex)
print(z,type(z))

## Identity Matrix

In [ ]:
i3 = np.identity(3)
print(i3,type(i3))

In [ ]:
i5 = np.identity(5,dtype = int)
print(i5)

## ndim


Dimensions of the matrix


In [ ]:
r2.ndim

In [ ]:
i5.ndim

## Shape

Returns number of rows and number of columns

In [ ]:
z.shape

In [ ]:
i3.shape

In [ ]:
r2.shape

## Size


Returns number of elements in the Matrix

In [ ]:
r2.size

In [ ]:
z.size

## itemsize

Memory occupied by single element

In [ ]:
z.itemsize  #complex

In [ ]:
i3.itemsize #float

In [ ]:
i5.itemsize #int