<a href="https://www.kaggle.com/code/aaradhyakulkarni/numpy-1-basics?scriptVersionId=177594814" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np

In [2]:
np.array([23,45,234,65,766,87]) #array

array([ 23,  45, 234,  65, 766,  87])

In [3]:
n = np.array([23,45,234,65,766,87]) #vector
print(n)

[ 23  45 234  65 766  87]


In [4]:
type(n)

numpy.ndarray

In [5]:
#Tensor

n3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
type(n3)

numpy.ndarray

## dtype


In [7]:
np.array([1,2,3],dtype = bool)

array([ True,  True,  True])

In [8]:
np.array([1,2,3],dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

## arrange

In [9]:
np.arange(1,30)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

## reshape

In [11]:
r1 = np.arange(0,15).reshape(3,5)
print(r1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [12]:
#3d Tensor
r2 = np.arange(8 , dtype = int).reshape(2,2,2)
print(r2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


## ones and zeroes

default datatype is float

In [13]:
o = np.ones((3,4),dtype = int)
print(o,type(o))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] <class 'numpy.ndarray'>


In [14]:
z = np.zeros((4,5),dtype = complex)
print(z,type(z))

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]] <class 'numpy.ndarray'>


## Identity Matrix

In [15]:
i3 = np.identity(3)
print(i3,type(i3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] <class 'numpy.ndarray'>


In [16]:
i5 = np.identity(5,dtype = int)
print(i5)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


## ndim


Dimensions of the matrix


In [17]:
r2.ndim

3

In [18]:
i5.ndim

2

## Shape

Returns number of rows and number of columns

In [19]:
z.shape

(4, 5)

In [20]:
i3.shape

(3, 3)

In [21]:
r2.shape

(2, 2, 2)

## Size


Returns number of elements in the Matrix

In [22]:
r2.size

8

In [23]:
z.size

20

## itemsize

Memory occupied by single element

In [24]:
z.itemsize  #complex

16

In [25]:
i3.itemsize #float

8

In [26]:
i5.itemsize #int

8