In [1]:
import numpy as np

# Array Operations


In [2]:
a1 = np.arange(1,13).reshape(3,4)
a2 = np.arange(13,25).reshape(3,4)

print('a1 = ',a1)
print('a2 = ',a2)

a1 =  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a2 =  [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


## Scalar Operations

In [3]:
a1 +3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
a1 -2

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [5]:
a1**2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [6]:
a2%10


array([[3, 4, 5, 6],
       [7, 8, 9, 0],
       [1, 2, 3, 4]])

## Relational Operations


In [7]:
a2 > 0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [8]:
a2 > 16

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [9]:
a1>10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

## Vector Operations

Operations in between matrices

In [10]:
a3 = a1+a2
a3

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [11]:
a4 = a1*a2
a4

array([[ 13,  28,  45,  64],
       [ 85, 108, 133, 160],
       [189, 220, 253, 288]])

In [12]:
a5 = a1/a2
a5.round(2)

array([[0.08, 0.14, 0.2 , 0.25],
       [0.29, 0.33, 0.37, 0.4 ],
       [0.43, 0.45, 0.48, 0.5 ]])

## Array Functions

In [13]:
a6 = np.random.random((3,3))
a6 = a6*100
a6 = a6.round(2)
a6

array([[98.91, 69.84, 45.05],
       [53.24, 43.6 , 45.6 ],
       [42.22, 50.51, 92.66]])

In [14]:
np.max(a6) , np.min(a6), np.sum(a6) , np.prod(a6)


(98.91, 42.22, 541.63, 6509033398593838.0)

If we want to find these row/column viz; use axis

In [15]:
print('Maximum of every row : ',np.max(a6 , axis=1))

Maximum of every row :  [98.91 53.24 92.66]


In [16]:
print('Maximum of every column : ',np.max(a6 , axis=0))

Maximum of every column :  [98.91 69.84 92.66]


In [17]:
print('Sum of every column: ',np.sum(a6 , axis =0))

Sum of every column:  [194.37 163.95 183.31]


In [18]:
print('Product of every row: ',np.prod(a6 , axis = 1))

Product of every row:  [311199.74172  105849.6384   197600.433652]


statistical functions are also available

In [19]:
# mean value of whole matrix
print('mean: ',np.mean(a6).round(2))
print('mediean: ',np.median(a6))
print('std: ',np.std(a6).round(2))
print('var: ',np.var(a6).round(2))

mean:  60.18
mediean:  50.51
std:  20.63
var:  425.43


In [20]:
#for every column
print('mean: ',a6.mean(axis=0))
print('median: ',np.median(a6,axis=0))
print('std: ',np.std(a6,axis=0))
print('var: ',a6.var(axis=0))

mean:  [64.79       54.65       61.10333333]
median:  [53.24 50.51 45.6 ]
std:  [24.54235658 11.105227   22.31506268]
var:  [602.32726667 123.32606667 497.96202222]


In [21]:
#similarly we can use trigonometric functions

## Dotproduct 


In [22]:
np.dot(a6,a2)  #shape should match

array([[3419.16, 3632.96, 3846.76, 4060.56],
       [2390.92, 2533.36, 2675.8 , 2818.24],
       [3353.39, 3538.78, 3724.17, 3909.56]])

In [23]:
# Similarly other functions such as .round() , .floor() , .ceil() can be used

### Indexing and Slicing is used for accessing elements

Slicing operation same as lists in python

In [24]:
#slicing on 1d array
i1 = np.arange(10)
i1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
i1[3:7]

array([3, 4, 5, 6])

In [26]:
i1[:6:2]

array([0, 2, 4])

In [27]:
i1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Indexing on 2d and 3d arrays. Similary applied to more dimensions

In [28]:
#indexing
i2 = np.array([[ 0, 1, 2, 3],
 [ 4, 5, 6, 7],
 [ 8, 9, 10, 11]])
i2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
i2[2,1]   #this also start from zero so a_3,2 = i2[2,1]
          # that is 2 = third row and 1 = second column

9

In [30]:
#3d tensor
i3 = np.array([[[0, 1],
 [2, 3]],
 [[4, 5],
 [6, 7]]])
i3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [31]:
i3[1,0,1]

5

Slicing on 2d and 3d arrays

In [32]:
i2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
# [ slice columns , slice rows]
# lets say we want 6,7 and 10 ,11 from i2
# so we slice 2nd and 3rd columns that is 1:3
# then we need last two rows that is 2:4 or 2:

i2[1:3 , 2:]

array([[ 6,  7],
       [10, 11]])

In [34]:
i2 [::2, ::3 ]

array([[ 0,  3],
       [ 8, 11]])

In [35]:
# for 3d 
# [ith matrix , ith row , ith column]

i4 = np.array([[[ 0, 1, 2],
 [ 3, 4, 5],
 [ 6, 7, 8]],
 [[ 9, 10, 11],
 [12, 13, 14],
 [15, 16, 17]],
 [[18, 19, 20],
 [21, 22, 23],
 [24, 25, 26]]])

i4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [36]:
i4[1,1,0] # mid matrix , second row , first columns

12

In [37]:
i4[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])