In [1]:
import numpy as np

### Iterating


In [2]:
a1 = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
for i in a1:
    print(i)

1
2
3
4
5
6
7
8
9


In [4]:
a2 = a1.reshape(3,3)
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
for i in a2:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [6]:
for i in np.nditer(a2):
    print(i)

1
2
3
4
5
6
7
8
9


### Transpose

In [7]:
#method 1
a3 = np.transpose(a2)
a3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [8]:
#method 2
a4 = a2.T
a4

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Ravel


In [9]:
a4.ravel()

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

### Stacking
- Horizhontal Stacking : np.hstack((a1,a2))
- Vertical Stacking    : np.vstack((a1,a2))

In [10]:
s1 = np.arange(1,10).reshape(3,3)
s2 = np.arange(31,40).reshape(3,3)

In [11]:
np.hstack((s1,s2))

array([[ 1,  2,  3, 31, 32, 33],
       [ 4,  5,  6, 34, 35, 36],
       [ 7,  8,  9, 37, 38, 39]])

In [12]:
np.vstack((s1,s2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [31, 32, 33],
       [34, 35, 36],
       [37, 38, 39]])

In [13]:
s3 = np.arange(21,27).reshape(3,2)

In [14]:
np.hstack((s1,s3))

array([[ 1,  2,  3, 21, 22],
       [ 4,  5,  6, 23, 24],
       [ 7,  8,  9, 25, 26]])

In [15]:
# np.vstack((s1,s3))
# error
#sizes should match for stacking

### Splitting 
- Horizhnotal SPlitting : hsplit(a1, n)
- Vertical Splitting    : vsplit(a1, n)

n = number of slpits

In [16]:
np.hsplit(s1 , 3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [17]:
s4 = np.arange(0,12).reshape(3,4)
s4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
np.hsplit(s4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [19]:
np.vsplit(s4 , 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]